name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate static site
      run: |
        mkdir site
        # Copiar todos os arquivos e pastas do repositório para a pasta 'site'
        rsync -av --exclude='site' ./ site/
        # Gerar o index.html básico
        echo "<html><body><h1>Arquivos</h1><ul>" > site/index.html
        ls -p | grep -v / | awk '{print "<li><a href=\""$1"\">" $1 "</a></li>"}' >> site/index.html
        echo "</ul></body></html>" >> site/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
